all:
  vars:
    ansible_user: admin
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
prod:
  hosts:
    client1:
       ansible_host: 192.168.99.11 # A remplacer par l'IP ou le DNS de votre machine cible
    client2:
       ansible_host: 192.168.99.12 # A remplacer par l'IP ou le DNS de votre machine cible
